name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Build (if any)
        run: npm run build --if-present

      - name: Run Tests
        run: npm test --if-present

      - name: Archive Function App
        run: zip -r functionapp.zip .

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: <your-function-app-name>  # change this
          package: functionapp.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
